### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by ricardojmendez** [noduslabs/infranodus#159]
Hi,

I'm getting an error during _npm install_ when attempting to follow the install instructions on OSX 10.10.2.   Working off the latest version on master (commit c60d40577b) and with npm 2.7.5

You'll find the npm-debug.log pasted below.

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
> 2 info using npm@2.7.5
> 3 info using node@v0.12.2
> 4 verbose node symlink /usr/local/bin/node
> 5 verbose install where, deps [ '/Users/the-username/Sources/infranodus',
> 5 verbose install   [ 'express', 'ejs', 'node-neo4j' ] ]
> 6 verbose install where, peers [ '/Users/the-username/Sources/infranodus', [] ]
> 7 info preinstall application-name@0.0.1
> 8 warn package.json transliteration.cyr@1.0.4 No repository field.
> 9 warn package.json util@0.10.3 util is also the name of a node core module.
> 10 verbose already installed skipping node-neo4j@* /Users/the-username/Sources/infranodus
> 11 verbose already installed skipping express@3.4.8 /Users/the-username/Sources/infranodus
> 12 verbose already installed skipping ejs@* /Users/the-username/Sources/infranodus
> 13 silly install resolved []
> 14 info build /Users/the-username/Sources/infranodus
> 15 verbose linkStuff [ false, false, false, '/Users/the-username/Sources' ]
> 16 info linkStuff application-name@0.0.1
> 17 verbose linkBins application-name@0.0.1
> 18 verbose linkMans application-name@0.0.1
> 19 verbose rebuildBundles application-name@0.0.1
> 20 verbose rebuildBundles [ '.bin',
> 20 verbose rebuildBundles   'async',
> 20 verbose rebuildBundles   'bcrypt-nodejs',
> 20 verbose rebuildBundles   'cheerio',
> 20 verbose rebuildBundles   'ejs',
> 20 verbose rebuildBundles   'evernote',
> 20 verbose rebuildBundles   'express',
> 20 verbose rebuildBundles   'flowdock-text',
> 20 verbose rebuildBundles   'google',
> 20 verbose rebuildBundles   'iconv-lite',
> 20 verbose rebuildBundles   'imap',
> 20 verbose rebuildBundles   'languagedetect',
> 20 verbose rebuildBundles   'mimelib',
> 20 verbose rebuildBundles   'natural',
> 20 verbose rebuildBundles   'node-lemmer',
> 20 verbose rebuildBundles   'node-neo4j',
> 20 verbose rebuildBundles   'node-uuid',
> 20 verbose rebuildBundles   'passport',
> 20 verbose rebuildBundles   'passport-local',
> 20 verbose rebuildBundles   'phantom',
> 20 verbose rebuildBundles   'socket.io',
> 20 verbose rebuildBundles   'string',
> 20 verbose rebuildBundles   'transliteration.cyr',
> 20 verbose rebuildBundles   'twit',
> 20 verbose rebuildBundles   'util' ]
> 21 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/async
> 22 info build /Users/the-username/Sources/infranodus/node_modules/async
> 23 info preinstall async@0.9.0
> 24 verbose linkStuff [ false,
> 24 verbose linkStuff   false,
> 24 verbose linkStuff   false,
> 24 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 25 info linkStuff async@0.9.0
> 26 verbose linkBins async@0.9.0
> 27 verbose linkMans async@0.9.0
> 28 verbose rebuildBundles async@0.9.0
> 29 info install async@0.9.0
> 30 info postinstall async@0.9.0
> 31 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/bcrypt-nodejs
> 32 info build /Users/the-username/Sources/infranodus/node_modules/bcrypt-nodejs
> 33 info preinstall bcrypt-nodejs@0.0.3
> 34 verbose linkStuff [ false,
> 34 verbose linkStuff   false,
> 34 verbose linkStuff   false,
> 34 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 35 info linkStuff bcrypt-nodejs@0.0.3
> 36 verbose linkBins bcrypt-nodejs@0.0.3
> 37 verbose linkMans bcrypt-nodejs@0.0.3
> 38 verbose rebuildBundles bcrypt-nodejs@0.0.3
> 39 info install bcrypt-nodejs@0.0.3
> 40 info postinstall bcrypt-nodejs@0.0.3
> 41 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/cheerio
> 42 info build /Users/the-username/Sources/infranodus/node_modules/cheerio
> 43 info preinstall cheerio@0.18.0
> 44 verbose linkStuff [ false,
> 44 verbose linkStuff   false,
> 44 verbose linkStuff   false,
> 44 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 45 info linkStuff cheerio@0.18.0
> 46 verbose linkBins cheerio@0.18.0
> 47 verbose linkMans cheerio@0.18.0
> 48 verbose rebuildBundles cheerio@0.18.0
> 49 verbose rebuildBundles [ 'CSSselect',
> 49 verbose rebuildBundles   'dom-serializer',
> 49 verbose rebuildBundles   'entities',
> 49 verbose rebuildBundles   'htmlparser2',
> 49 verbose rebuildBundles   'lodash' ]
> 50 info install cheerio@0.18.0
> 51 info postinstall cheerio@0.18.0
> 52 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/evernote
> 53 info build /Users/the-username/Sources/infranodus/node_modules/evernote
> 54 info preinstall evernote@1.25.3
> 55 verbose linkStuff [ false,
> 55 verbose linkStuff   false,
> 55 verbose linkStuff   false,
> 55 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 56 info linkStuff evernote@1.25.3
> 57 verbose linkBins evernote@1.25.3
> 58 verbose linkMans evernote@1.25.3
> 59 verbose rebuildBundles evernote@1.25.3
> 60 verbose rebuildBundles [ 'oauth' ]
> 61 info install evernote@1.25.3
> 62 info postinstall evernote@1.25.3
> 63 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/flowdock-text
> 64 info build /Users/the-username/Sources/infranodus/node_modules/flowdock-text
> 65 info preinstall flowdock-text@0.1.5
> 66 verbose linkStuff [ false,
> 66 verbose linkStuff   false,
> 66 verbose linkStuff   false,
> 66 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 67 info linkStuff flowdock-text@0.1.5
> 68 verbose linkBins flowdock-text@0.1.5
> 69 verbose linkMans flowdock-text@0.1.5
> 70 verbose rebuildBundles flowdock-text@0.1.5
> 71 info install flowdock-text@0.1.5
> 72 info postinstall flowdock-text@0.1.5
> 73 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/google
> 74 info build /Users/the-username/Sources/infranodus/node_modules/google
> 75 info preinstall google@0.6.0
> 76 verbose linkStuff [ false,
> 76 verbose linkStuff   false,
> 76 verbose linkStuff   false,
> 76 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 77 info linkStuff google@0.6.0
> 78 verbose linkBins google@0.6.0
> 79 verbose link bins [ { google: './bin/google' },
> 79 verbose link bins   '/Users/the-username/Sources/infranodus/node_modules/.bin',
> 79 verbose link bins   false ]
> 80 verbose linkMans google@0.6.0
> 81 verbose rebuildBundles google@0.6.0
> 82 verbose rebuildBundles [ 'cheerio', 'commander', 'fast-csv', 'request' ]
> 83 silly gentlyRm /Users/the-username/Sources/infranodus/node_modules/.bin/google is being purged
> 84 verbose gentlyRm don't care about contents; nuking /Users/the-username/Sources/infranodus/node_modules/.bin/google
> 85 silly vacuum-fs purging /Users/the-username/Sources/infranodus/node_modules/.bin/google
> 86 silly vacuum-fs quitting because other entries in /Users/the-username/Sources/infranodus/node_modules/.bin
> 87 info install google@0.6.0
> 88 info postinstall google@0.6.0
> 89 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/iconv-lite
> 90 info build /Users/the-username/Sources/infranodus/node_modules/iconv-lite
> 91 info preinstall iconv-lite@0.4.4
> 92 verbose linkStuff [ false,
> 92 verbose linkStuff   false,
> 92 verbose linkStuff   false,
> 92 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 93 info linkStuff iconv-lite@0.4.4
> 94 verbose linkBins iconv-lite@0.4.4
> 95 verbose linkMans iconv-lite@0.4.4
> 96 verbose rebuildBundles iconv-lite@0.4.4
> 97 info install iconv-lite@0.4.4
> 98 info postinstall iconv-lite@0.4.4
> 99 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/imap
> 100 info build /Users/the-username/Sources/infranodus/node_modules/imap
> 101 info preinstall imap@0.8.12
> 102 verbose linkStuff [ false,
> 102 verbose linkStuff   false,
> 102 verbose linkStuff   false,
> 102 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 103 info linkStuff imap@0.8.12
> 104 verbose linkBins imap@0.8.12
> 105 verbose linkMans imap@0.8.12
> 106 verbose rebuildBundles imap@0.8.12
> 107 verbose rebuildBundles [ 'readable-stream', 'utf7' ]
> 108 info install imap@0.8.12
> 109 info postinstall imap@0.8.12
> 110 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/languagedetect
> 111 info build /Users/the-username/Sources/infranodus/node_modules/languagedetect
> 112 info preinstall languagedetect@1.1.0
> 113 verbose linkStuff [ false,
> 113 verbose linkStuff   false,
> 113 verbose linkStuff   false,
> 113 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 114 info linkStuff languagedetect@1.1.0
> 115 verbose linkBins languagedetect@1.1.0
> 116 verbose linkMans languagedetect@1.1.0
> 117 verbose rebuildBundles languagedetect@1.1.0
> 118 info install languagedetect@1.1.0
> 119 info postinstall languagedetect@1.1.0
> 120 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/mimelib
> 121 info build /Users/the-username/Sources/infranodus/node_modules/mimelib
> 122 info preinstall mimelib@0.2.18
> 123 verbose linkStuff [ false,
> 123 verbose linkStuff   false,
> 123 verbose linkStuff   false,
> 123 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 124 info linkStuff mimelib@0.2.18
> 125 verbose linkBins mimelib@0.2.18
> 126 verbose linkMans mimelib@0.2.18
> 127 verbose rebuildBundles mimelib@0.2.18
> 128 verbose rebuildBundles [ 'addressparser', 'encoding' ]
> 129 info install mimelib@0.2.18
> 130 info postinstall mimelib@0.2.18
> 131 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/natural
> 132 info build /Users/the-username/Sources/infranodus/node_modules/natural
> 133 info preinstall natural@0.1.27
> 134 verbose linkStuff [ false,
> 134 verbose linkStuff   false,
> 134 verbose linkStuff   false,
> 134 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 135 info linkStuff natural@0.1.27
> 136 verbose linkBins natural@0.1.27
> 137 verbose linkMans natural@0.1.27
> 138 verbose rebuildBundles natural@0.1.27
> 139 verbose rebuildBundles [ '.bin', 'apparatus', 'sylvester', 'underscore', 'uubench' ]
> 140 info install natural@0.1.27
> 141 info postinstall natural@0.1.27
> 142 verbose rebuild bundle /Users/the-username/Sources/infranodus/node_modules/node-lemmer
> 143 info build /Users/the-username/Sources/infranodus/node_modules/node-lemmer
> 144 info preinstall node-lemmer@0.1.0
> 145 verbose linkStuff [ false,
> 145 verbose linkStuff   false,
> 145 verbose linkStuff   false,
> 145 verbose linkStuff   '/Users/the-username/Sources/infranodus/node_modules' ]
> 146 info linkStuff node-lemmer@0.1.0
> 147 verbose linkBins node-lemmer@0.1.0
> 148 verbose linkMans node-lemmer@0.1.0
> 149 verbose rebuildBundles node-lemmer@0.1.0
> 150 info install node-lemmer@0.1.0
> 151 verbose unsafe-perm in lifecycle true
> 152 info node-lemmer@0.1.0 Failed to exec install script
> 153 verbose stack Error: node-lemmer@0.1.0 install: `node-gyp rebuild`
> 153 verbose stack Exit status 1
> 153 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
> 153 verbose stack     at EventEmitter.emit (events.js:110:17)
> 153 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
> 153 verbose stack     at ChildProcess.emit (events.js:110:17)
> 153 verbose stack     at maybeClose (child_process.js:1015:16)
> 153 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> 154 verbose pkgid node-lemmer@0.1.0
> 155 verbose cwd /Users/the-username/Sources/infranodus/node_modules
> 156 error Darwin 14.1.0
> 157 error argv "node" "/usr/local/bin/npm" "install"
> 158 error node v0.12.2
> 159 error npm  v2.7.5
> 160 error code ELIFECYCLE
> 161 error node-lemmer@0.1.0 install: `node-gyp rebuild`
> 161 error Exit status 1
> 162 error Failed at the node-lemmer@0.1.0 install script 'node-gyp rebuild'.
> 162 error This is most likely a problem with the node-lemmer package,
> 162 error not with npm itself.
> 162 error Tell the author that this fails on your system:
> 162 error     node-gyp rebuild
> 162 error You can get their info via:
> 162 error     npm owner ls node-lemmer
> 162 error There is likely additional logging output above.
> 163 verbose exit [ 1, true ]

**Comment by deemeetree** [comment]
Hey what's your node.js version?

**Comment by ricardojmendez** [comment]
It's v0.12.2.  Since that seems to have been released on 2015.03.31, I expect it was the same one as when I tested.
