### ISSUE TITLE
chargebee?

### ISSUE THREAD

**Issue by j2l** [noduslabs/infranodus#273]
At running from source locally, I get:
```
> node app.js

E:\infranodus\options.js:89
    exports.chargebee.site = parsed['chargebee']['site'];
                                                ^

TypeError: Cannot read property 'site' of undefined
    at Object.<anonymous> (E:\infranodus\options.js:89:49)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\infranodus\lib\entry.js:21:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! InfraNodus@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the InfraNodus@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Any idea?

**Comment by j2l** [comment]
commenting the chargebee section fixed it
