### ISSUE TITLE
Error starting Infranodus

### ISSUE THREAD

**Issue by AdhamAlHarazi** [noduslabs/infranodus#290]
I followed the installation guide, and when I want to run Infranodus through `npm install` I run into the following error:  - 

`
> InfraNodus@1.0.0 start /Users/adham/infranodus
> node app.js

/Users/adham/infranodus/options.js:88
    exports.chargebee.site = parsed['chargebee']['site']
                                                ^

TypeError: Cannot read property 'site' of undefined
    at Object.<anonymous> (/Users/adham/infranodus/options.js:88:49)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/adham/infranodus/lib/entry.js:20:15)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! InfraNodus@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the InfraNodus@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adham/.npm/_logs/2019-08-20T16_54_27_036Z-debug.log
`
Any help is appreciated.

**Comment by michaelrlevy** [comment]
I am having the same issue.

**Comment by deemeetree** [comment]
Hello, please, see the new updates to the `config.sample.json` file, which address this. Update the version and follow the installation instruction in the README. Let me know how it works!

**Comment by michaelrlevy** [comment]
Dmitry, this took care of my problem. Thanks! Infrandous is a really interesting application.
