### ISSUE TITLE
Not able to sign-up in local version

### ISSUE THREAD

**Issue by sagar2agrawal** [noduslabs/infranodus#310]
Neo4j version: 4.2

Text body normalized: sundaypyjamas
D:\Software\development\infranodus-master\lib\user.js:298
        fn(null, uid.data[0])
                     ^

 

TypeError: Cannot read property 'data' of null
    at D:\Software\development\infranodus-master\lib\user.js:298:22
    at D:\Software\development\infranodus-master\node_modules\node-neo4j\lib\main.js:1567:6
    at Request.callback (D:\Software\development\infranodus-master\node_modules\superagent\lib\node\index.js:748:3)
    at Request.<anonymous> (D:\Software\development\infranodus-master\node_modules\superagent\lib\node\index.js:135:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (D:\Software\development\infranodus-master\node_modules\superagent\lib\node\index.js:938:12)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

--------------------------------------------------------------------------------------------------------------------
The neo4j database is empty and i am not sure if we have to do anything if the database is version 4.2

**Comment by siriuslea** [comment]
Hi sagar2agrawal How did you resolve this?

**Comment by deemeetree** [comment]
Hey the best is if you use Neo4J up to 3.5.17 version.

And you need to also make sure you follow all the installation and set up instructions.

**Comment by siriuslea** [comment]
Thanks for the response! I already run Neo4j v.4 (for other uses) but perhaps I still have a copy of 3.5 installed so I will try that. Is the issue with indexing in v.4?
