### ISSUE TITLE
Node versions or something similar

### ISSUE THREAD

**Issue by StoltHD** [noduslabs/infranodus#312]
I was stupid enough to upgrade my Node installation on my Windows 10 installation, and now I get a "express-session deprecated req.secret;" error, this gives a 500 internal server error when trying to use infranodus...

I also tried to install infranodus on WSL 2 (Debian), but the Node installation there was also a newer version of Node.js (10+)

I just wanted to ask if there was any plans to move infranodus to a newer node version, or if anyone can in an easy and understandable (im not a developer) way explain how I can configure node, express and infranodus to work (if possible)..

Or what versions of node that can be used or are recommended ( I think Im going to install Infranodus on a VM instead of WSL)

Thanks for any information

This is the startup message I get:
\infranodus> node app.js
express-session deprecated req.secret; provide secret option app.js:86:9
(node:168432) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Express server listening on port 3000

...........
And this is some of the error-messages when trying to open Infranodus in browser:

Error: secret option required for sessions
    at session (...\infranodus\node_modules\express-session\index.js:200:12)
    at Layer.handle [as handle_request] (...\infranodus\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\infranodus\node_modules\express\lib\router\index.js:317:13)
    at ...\infranodus\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (...\infranodus\node_modules\express\lib\router\index.js:335:12)
    at next (...\infranodus\node_modules\express\lib\router\index.js:275:10)
    at methodOverride (...\infranodus\node_modules\method-override\index.js:65:14)
    at Layer.handle [as handle_request] (...\infranodus\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\infranodus\node_modules\express\lib\router\index.js:317:13)
    at ...\infranodus\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (...\infranodus\node_modules\express\lib\router\index.js:335:12)
    at next (...\infranodus\node_modules\express\lib\router\index.js:275:10)
    at favicon (...\infranodus\node_modules\serve-favicon\index.js:68:7)
    at Layer.handle [as handle_request] (...\infranodus\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\infranodus\node_modules\express\lib\router\index.js:317:13)
    at ...\infranodus\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (...\infranodus\node_modules\express\lib\router\index.js:335:12)
    at next (...\infranodus\node_modules\express\lib\router\index.js:275:10)
    at expressInit (...\infranodus\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (...\infranodus\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\infranodus\node_modules\express\lib\router\index.js:317:13)
    at ...\infranodus\node_modules\express\lib\router\index.js:284:7

........................

PS. I know I fxxxxx this installation up (node version v14.2.0 on windows 10)
(Node v13.7.0 on WSL 2 - Debian)

**Comment by deemeetree** [comment]
Hello

InfraNodus currently runs on Node 12 which is not so old and is relatively reliable.

The only thing I can suggest is to Google how you can use NVM to manage your node versions. This way you can have several of them installed and switch between them depending on your requirements.

**Comment by StoltHD** [comment]
Yes, It was a big mistakee of me to run the upgrade ... so I'm going to do
a clean install of WSL now after change of hardware ...

I will look into NVM to, thanks ...

Thanks for answering :-)

ons. 22. jul. 2020 kl. 16:33 skrev Dmitry Paranyushkin <
notifications@github.com>:
