### ISSUE TITLE
Error: 500 internal server errors

### ISSUE THREAD

**Issue by Muciojaziel** [noduslabs/infranodus#313]
**Importing a text file, an error occurs, I am not sure what happens, in the neo4j database some data is stored. However, the graphics are not generated. In addition, and a message appears in the browser: 500 internal server error.
In the terminal, these errors are shown below:**

CALL  apoc.index.relationships('TO','context:undefined')  YIELD rel, start, end  WITH DISTINCT COLLECT(DISTINCT rel) AS rs, start, end  ORDER BY SIZE(rs) DESC LIMIT 300 WITH COLLECT(start.uid) AS cs, COLLECT(end.uid) AS ce  CALL  apoc.index.relationships('TO','context:undefined')  YIELD rel, start, end WITH rel, start, end  WHERE ((start.uid IN cs OR start.uid IN ce) AND (end.uid IN cs OR end.uid IN ce))  RETURN DISTINCT start.uid AS source_id, start.name AS source_name,  end.uid AS target_id, end.name AS target_name, rel.uid AS edge_id,  rel.context AS context_id, rel.statement AS statement_id, rel.weight AS weight 
Error: HTTP Error 400 when running the cypher query against neo4j.
CypherExecutionException: There is no procedure with the name `apoc.index.relationships` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
    at /home/mucio/Desktop/ProjsWeb/infranodus/node_modules/node-neo4j/lib/main.js:1570:15
    at Request.callback (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/superagent/lib/node/index.js:748:3)
    at Request.<anonymous> (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/superagent/lib/node/index.js:135:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/superagent/lib/node/index.js:938:12)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
GET /api/user/nodes/inovo 400 42.519 ms - 3133
GET /images/error/404 404 9.638 ms - 1909
GET /images/timer-blue.png 200 1.192 ms - 1407
reqbody
{ entry: { body: 'dfasdfasdf' },
  addedContexts: 'inovo',
  context: 'inovo',
  selectedContexts: '',
  statementid: '',
  timestamp: '' }
contexts submitted
[ 'inovo' ]
contexts uniqualized
[ 'inovo' ]
contexts retrieved from db
[ { uid: '36120950-c49e-11ea-9197-51b7319e54b6', name: 'inovo' } ]
Text body normalized: dfasdfasdf
We are processing: dfasdfasdf
Lemmas final obtained:
[ 'dfasdfasdf' ]
Hashtags extracted: dfasdfasdf
extracted mentions: 

**elsewhere:**
Neo4jError: connect ECONNREFUSED 127.0.0.1:7687

    at captureStacktrace (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/neo4j-driver/lib/v1/result.js:199:15)
    at new Result (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/neo4j-driver/lib/v1/result.js:65:19)
    at Session._run (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/neo4j-driver/lib/v1/session.js:152:14)
    at Session.run (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/neo4j-driver/lib/v1/session.js:130:19)
    at /home/mucio/Desktop/ProjsWeb/infranodus/routes/entries.js:404:26
    at /home/mucio/Desktop/ProjsWeb/infranodus/lib/entry.js:77:13
    at Function.CypherQuery.addStatement (/home/mucio/Desktop/ProjsWeb/infranodus/lib/db/neo4j.js:604:5)
    at Entry.savetrans (/home/mucio/Desktop/ProjsWeb/infranodus/lib/entry.js:69:17)
    at /home/mucio/Desktop/ProjsWeb/infranodus/routes/entries.js:396:23
    at submitEntry (/home/mucio/Desktop/ProjsWeb/infranodus/routes/entries.js:378:21)
    at /home/mucio/Desktop/ProjsWeb/infranodus/routes/entries.js:363:21
    at fn (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/home/mucio/Desktop/ProjsWeb/infranodus/node_modules/async/lib/async.js:554:34)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)

POST /post 500 102.627 ms - 3134
user disconnected
users left
undefined
1

I'm using
SO: Linux 18.04
Neo4j 3.5.0.12

**Comment by deemeetree** [comment]
It looks like you can't connect to the DB. You need to check if your local environment allows access through the ports specified.

**Comment by Muciojaziel** [comment]
This is a little strange, as I inform the user to the database in the JSON configuration file.  But, I will check and return the results here, thank you.

**Comment by cristianvasquez** [comment]
Since the log says: 'There is no procedure with the name apoc.index.relationships' perhaps the APOC plugin is not installed in NEO4J (https://neo4j-contrib.github.io/neo4j-apoc-procedures/index33.html)
