### ISSUE TITLE
Cann't connect local

### ISSUE THREAD

**Issue by silvadenisaraujo** [noduslabs/infranodus#317]
Hello team, I followed the tutorial to install the local version of infranodus in osx, but when I go to the page with the secret-code and hit the button to register, I receive the following error:

Anything missing?

**Error:**
```javascript
GET /fonts/IstokWeb-Regular.ttf 304 0.563 ms - -
Text body normalized: denis
/Users/denis/Codes/infranodus/lib/user.js:298
        fn(null, uid.data[0])
                     ^

TypeError: Cannot read property 'data' of null
    at /Users/denis/Codes/infranodus/lib/user.js:298:22
    at /Users/denis/Codes/infranodus/node_modules/node-neo4j/lib/main.js:1567:6
    at Request.callback (/Users/denis/Codes/infranodus/node_modules/superagent/lib/node/index.js:748:3)
    at Request.<anonymous> (/Users/denis/Codes/infranodus/node_modules/superagent/lib/node/index.js:135:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/Users/denis/Codes/infranodus/node_modules/superagent/lib/node/index.js:938:12)
```

**Comment by silvadenisaraujo** [comment]
FYI @smileydarkling

**Comment by cristianvasquez** [comment]
I noticed that I get that error when using neo4j > 4.0. I tried with Neo4J 3.5 (with apoc plugin) and it worked.

**Comment by juandps** [comment]
I have the same problem when trying to sign up?

**Comment by ctyler9** [comment]
Run it through the VM and it should work. What I encountered when trying to run it locally with the older version of neo4j is that it also required an older version of Java... as I started the pull the thread more and more it got more complex. Just stay within the VM they do a good job creating the env.
